apiVersion: apps/v1
kind: Deployment
metadata: {name: ml-api}
spec:
  replicas: 1
  selector: {matchLabels: {app: ml-api}}
  template:
    metadata: {labels: {app: ml-api}}
    spec:
      containers:
      - name: api
        image: ml-api:0.1
        ports: [{containerPort: 80}]
---
apiVersion: v1
kind: Service
metadata: {name: ml-api-svc}
spec:
  selector: {app: ml-api}
  ports: [{port: 80, targetPort: 80}]
