replicaCount: 1

image:
  repository: ml-api
  tag: "0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

containerPort: 8000
readinessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 5

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false
