name: CI
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: {contents: read, packages: read}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
      - run: docker buildx build --platform linux/arm64 -t ml-api:${{ github.sha }} .

      - uses: helm/kind-action@v1
        with:
          cluster_name: lab
          wait: true

      - run: kind load docker-image ml-api:${{ github.sha }} --name lab
      - run: helm upgrade --install ml-api ./chart --set image.tag=${{ github.sha }}
      - run: kubectl rollout status deployment/ml-api --timeout=90s
