name: CI
on:
  push:
    branches: [main]
  pull_request:           # for PR
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: {contents: read, packages: read}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
      - run: docker buildx build --platform linux/arm64 -t ml-api:${{ github.sha }} --load .

      - uses: helm/kind-action@v1
        with:
          cluster_name: lab
          wait: 120s

      - run: kind load docker-image ml-api:${{ github.sha }} --name lab
      - run: | 
          helm upgrade --install ml-api ./ml-api \
            --set image.tag=${{ github.sha }}

      - run: kubectl get pods -l app.kubernetes.io/instance=ml-api -o wide
      - run: |
          kubectl logs deployment/ml-api --tail=50 || true

      - run: kubectl rollout status deployment/ml-api --timeout=200s
